[language-server.typos]
command = "typos-lsp"
config.diagnosticSeverity = "Warning"

[[language]]
name = "markdown"
language-servers = ["typos", "marksman"]

[language-server.tinymist.config]
outputPath = "$root/build/$dir/$name"
exportPdf = "onSave"
lint.enabled = true
preview.background.args = [ "--data-plane-host=127.0.0.1:23635" ]
preview.background.enabled = true


[[language]]
name = "typst"
language-servers = ["tinymist", "typos"]
formatter = { command = "typstyle" }
auto-format = true
