name: "Compile"
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: .#ci
      - run: just
      - name: Publish PDF
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: 'build/*'
            
  release:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get current date
        id: date
        run: echo "tag=$(date)" >> "$GITHUB_OUTPUT"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.tag }}
        run: |
          gh release create "$tag" \
              --title="Release $tag" \
              --repo="$GITHUB_REPOSITORY" \
              'artifacts/outputs/*'
